### ISSUE TITLE
Some site design - ideas

### ISSUE THREAD

**Issue by Yopai** [LorcanaJSON/LorcanaJSON-website#2]
To make the site visually more clean, there are a couple of options.

My ideas :

* use Bootstrap as a base
* use a free template as a base, like https://www.free-css.com/free-css-templates/page292/simply-amazed
* ...

**Comment by Didero** [comment]
I agree that the site looks very basic currently, though I also like the clean simple look and the instant loading.
To especially keep the latter, I don't want to use any large Javascript or CSS libraries, or external fonts, all of which would also make maintenance a lot harder and more time-consuming.

**Comment by Yopai** [comment]
See my new proposal https://github.com/LorcanaJSON/LorcanaJSON-website/pull/4 for something more simple (that is, just some css rules)


Don't hesitate to ask me questions, or propose a view of what a "Better site design" (your own words) can be for you.

**Comment by Didero** [comment]
That proposal looks great, thanks!
There's a few small things I'm not sure about, like the question mark in front of optional fields, the icons in the 'Downloads' table before links, and how it's hard to see that the JSON link and MD5 link are separate links, but those are minor things. It looks a lot better than what I made!

The official Lorcana site has a Resources page with, among other things, [this color guide](https://brand.ravensburger-group.com/d/e1vhRSQ7WeNy/color#/lorcana-colors/the-disney-lorcana-brand-colors-1687894099), which would be fun to implement.
Would you mind if I accept this proposal and then change some things about it, like those colors and the download links? Or would you rather we discuss the changes together, since it's your design?

**Comment by Yopai** [comment]
Hi,

Happy to hear that, you're welcome !

I just pushed another commit :
* I removed the question marks
* I put back "md5" on the next line
* And I applied the template to changelog page, with some specific styles for this page
  * Dynamically generated TOC of the versions on the left
  * Permalinks put in a box on the right
  * version format shown has badges
* I used the Lorcana colors and added the logo

Of course, you can improve it ! (You may even add commits on the branch of my fork, if I correctly understand the Github help pages)
Some of your remarks are about ideas I put to see what it looks like, and be improved. Typically :
* the question marks were here as a tentative to make optional fields visually different. I'll try other things.
* the download icons are meant to visually enhance the download links
So you can tell me what you like / dislike, and/or make the changes yourself. It's your project.

:)

**Comment by Yopai** [comment]
Oh, by the way, one last thing : as I'm color-blind, color associations may seem awful for one who isn't. Don't hesitate to tell me !

**Comment by Yopai** [comment]
By the way, in the last minute I tried something for the links, but I'm not fan of it.

**Comment by Didero** [comment]
Sorry for being quiet for a while, I suddenly got very busy with verifying and publishing the cards for Set 4.
But that's now done!
In the process I did break your merge request by adding a changelog entry and updating the index page though, sorry.

But the new colors look good, thanks for the update.
On the changelog page, the list of each changelog entry is a good idea. The links to the index page sections look a bit weird there though, instead of the whole list just a 'Back to main' link would be better.

**Comment by Yopai** [comment]
Thanks for set 4; I'll merge your commit into my MR.

For the menu, well... My opinion was rather to consider that you have the full menu on every page of the site (like a menu on every site)
But it's your site, so I'll get the "back to main" item back in place of the menu.

**Comment by Yopai** [comment]
That's done !

You can check, and merge (I suggest you squash the commits when doing the merge, there is no real need to pollute the history with back and forth)

**Comment by Didero** [comment]
Sorry I've been quiet for so long again, I was fighting with parsing the cards from 'Deep Trouble'.
I've just merged your redesign. I'll make some small changes, since I just noticed that the footer doesn't show up.

Again, thanks very much for your work, it really elevates the website!!

**Comment by Didero** [comment]
I made some small changes, and some much-needed updates to the actual texts, since quite a few of it was a bit behind, whoops.
I also just put the redesign live, so now everybody can admire your work!
I put the old design [here](https://lorcanajson.org/old/) for now, for comparison
